[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login-v2"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout-v2"
  status = 200

[[redirects]]
  from = "/api/session"
  to = "/.netlify/functions/session-v2"
  status = 200

[[redirects]]
  from = "/api/content"
  to = "/.netlify/functions/content-v2"
  status = 200

[[redirects]]
  from = "/api/public-content"
  to = "/.netlify/functions/public-content"
  status = 200

[[redirects]]
  from = "/api/quote-submit"
  to = "/.netlify/functions/quote-submit"
  status = 200
